### PR TITLE
Bare-bones CRUD restful interface

### PR DESCRIPTION
**Pull request by dleehr**
JSON/REST interface for resources `handovers`, `drafts`, `users`. Needs documentation

### CODE REVIEW

**Comment by dleehr** [comment]
@johnbradley This is very early but wanted to get some feedback. I'll be adding documentation on how to use it from `cURL` or requests, as well as how to install/run. Essentially it's this

1. Run with `python handover_api/app.py`
2. POST: `curl -X POST -H "Content-Type: application/json" -d '{"from_user_id": "sender-dds-udid", "project_id": "existing-project-udid", "to_user_id": "recip-dds-udid"}' http://127.0.0.1:5000/handovers/`

**Comment by johnbradley** [comment]
After running `python handover_api/app.py` in a separate window
The `curl` command above returns a 405:
{
    "message": "The method is not allowed for the requested URL."
}
I see this in the python terminal:
`127.0.0.1 - - [29/Mar/2016 08:46:46] "POST /handovers/ HTTP/1.1" 405 -`

GET does work however.
`curl X GET -H "Content-Type: application/json" -d '{"from_user_id": "sender-dds-udid", "project_id": "existing-project-udid", "to_user_id": "recip-dds-udid"}' http://127.0.0.1:5000/handovers/`
returns 200:
`{
  "results": []
}`

**Comment by johnbradley** [comment]
After checking out the correct branch I was able to send a handover message from DukeDSClient  :+1:.  

If I try to handover twice again I receive a 400 with 
`{
    "message": "Unable to create handover: (sqlite3.IntegrityError) UNIQUE constraint failed: handover_model.project_id [SQL: u'INSERT INTO handover_model (project_id, from_user_id, to_user_id, state) VALUES (?, ?, ?, ?)'] [parameters: (u'e144fca1-0e1e-4c39-b658-032829d9c2b3', u'5dd78297-1604-457c-87c1-e3a792be16b9', u'77882934-5923-4d4b-b202-e4cf671e5439', 'Initiated')]"
}`

**Comment by johnbradley** [comment]
The table names in the database are a little funky (handover_model  user_model).

**Comment by dleehr** [comment]
> The table names in the database are a little funky (handover_model user_model).

Ah. Those are the defaults that flask_sqlalchemy. But I can specify them.

**Comment by dleehr** [comment]
> If I try to handover twice again I receive a 400 with ... `UNIQUE constraint failed`

That was by design - The message isn't friendly but if the client tries to hand-over the same project uuid twice it should fail, right?

**Comment by dleehr** [comment]
While this was an interesting line, I've rebuilt this app using django and djangorestframework. In just a couple hours I've rebuilt and surpassed the functionality here. The API is the same, but the framework is a better fit for this project. There are many best practices available and a rich community.

**Pull request closed without merging**
