### PR TITLE
Mail draft

### PR DESCRIPTION
**Pull request by dleehr**
Implements #5

### CODE REVIEW

**Comment by dleehr** [comment]
@johnbradley Please review.

Some notes

1. API root has changed to /api/v1/
2. Sending a draft is a two step process. First, create the resource, then call its send action. Handover will follow the same convention
3. For project organization, a django project has one or more apps. Historically I've crammed everything into a single app, but here I'm trying to break things apart. Welcome any feedback on the organization here.

**Comment by johnbradley** [comment]
I think you want this in the README:
`pip install -r requirements.txt `
instead of 
`pip install requirements.txt`

Registering a user needs a slash at the end of the url.
Otherwise you get back html error: 
`...You called this URL via POST, but the URL doesn&#39;t end in a slash and you have APPEND_SLASH set...`
Might be nice to send back error in json format but not a big deal.
Fixed curl:
```
        $ curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"dds_id":"your-uuid","api_key":"your-user-key"}' \
          http://127.0.0.1:8000/api/v1/users/
          {"id":1,"url":"http://127.0.0.1:8000/api/v1/users/1/","dds_id":"xxxx","api_key":"xxxx"}
```
Sending

**Comment by johnbradley** [comment]
I didn't have auth in my .ddsclient data and got an error about connecting to DukeDS(which is correct).
But it looks like it failed in trying to raise that error:
```
    raise ValueError(e, message='Unable to retrieve information from DukeDS')
TypeError: ValueError does not take keyword arguments
```

**Comment by johnbradley** [comment]
`handover_api/models.py` could use some class level comments.
User is pretty obvious but State, Handover and Draft are a little abstract.

`handover_api/utils.py` send_draft could use a comment and what the draft param is(handover_api/Draft?). 
Also the giant 'signature' value is temporary right?

**Comment by johnbradley** [comment]
Are you going to make a separate package for handover? If so you might want to move dds_util somewhere else since it can probably be re-used by both handover and mail_draft.
DDSUtil could use some comments as well.

I was able to run the unit tests without error and exercise the api from the command line. :+1:

**Comment by dleehr** [comment]
I wasn't planning on putting handover stuff in a separate package. I was going to put it in what's now mail_draft, but probably need to refactor that name.

**Comment by dleehr** [comment]
Maybe an `actions` or a `communication` package instead of `mail_draft`? I find it's easier to navigate projects laid out by function

**Comment by johnbradley** [comment]
Looks like we throw a 'Already notified' error if we have already sent the mail.
What about the use case where we send the user mail_draft and they don't respond.
In that case we want to re-send the email. Is there a way to achieve that?

**Comment by johnbradley** [comment]
Changing the package name sounds good to me.

**Comment by dleehr** [comment]
Change the initial state to 'New'

**Comment by dleehr** [comment]
Feedback moved to new issue

**Pull request merged**
